// Íconos SVG (lucide) referenciados por nombre desde la capa de datos.
// Reemplaza a los emojis: render consistente entre dispositivos.
import {
  AlarmClock, Armchair, AtSign, Atom, Bath, Blocks, BookOpen, BookUser,
  Briefcase, Bug, Building2, Bus, Cake, CalendarDays, Car, CarFront, Check,
  CircleDot, CircleHelp, Clapperboard, CloudSun, CookingPot, Croissant, CupSoda,
  Dice5, DoorOpen, Dumbbell, Fish, Flag, Flower2, Gamepad2, Gem, Ghost, Gift,
  Globe, Goal, GraduationCap, Guitar, Hand, Heart, Infinity as InfinityIcon,
  Landmark, Languages, Layers, Luggage, MapPin, MessageCircle, Mountain, Music,
  Orbit, Palette, PartyPopper, PawPrint, Ruler, Salad, Settings, Shield, Shirt,
  ShoppingCart, Smartphone, Snowflake, Sparkles, Star, Tag, Timer, Trophy, Tv,
  Type, Umbrella, User, Utensils, Volume2, Wrench, X, Zap,
  type LucideIcon,
} from 'lucide-react';

const icons: Record<string, LucideIcon> = {
  'alarm-clock': AlarmClock,
  armchair: Armchair,
  'book-user': BookUser,
  briefcase: Briefcase,
  'building-2': Building2,
  bus: Bus,
  'calendar-days': CalendarDays,
  check: Check,
  clapperboard: Clapperboard,
  'cooking-pot': CookingPot,
  'cup-soda': CupSoda,
  dumbbell: Dumbbell,
  flag: Flag,
  orbit: Orbit,
  'flower-2': Flower2,
  ghost: Ghost,
  globe: Globe,
  guitar: Guitar,
  hand: Hand,
  infinity: InfinityIcon,
  languages: Languages,
  layers: Layers,
  'message-circle': MessageCircle,
  music: Music,
  palette: Palette,
  'paw-print': PawPrint,
  salad: Salad,
  settings: Settings,
  shirt: Shirt,
  smartphone: Smartphone,
  star: Star,
  tag: Tag,
  timer: Timer,
  trophy: Trophy,
  tv: Tv,
  umbrella: Umbrella,
  user: User,
  utensils: Utensils,
  wrench: Wrench,
  x: X,
  'at-sign': AtSign,
  atom: Atom,
  bath: Bath,
  blocks: Blocks,
  'book-open': BookOpen,
  bug: Bug,
  cake: Cake,
  car: Car,
  'car-front': CarFront,
  'circle-dot': CircleDot,
  'cloud-sun': CloudSun,
  croissant: Croissant,
  'dice-5': Dice5,
  'door-open': DoorOpen,
  fish: Fish,
  'gamepad-2': Gamepad2,
  gem: Gem,
  gift: Gift,
  goal: Goal,
  'graduation-cap': GraduationCap,
  heart: Heart,
  landmark: Landmark,
  luggage: Luggage,
  'map-pin': MapPin,
  mountain: Mountain,
  'party-popper': PartyPopper,
  ruler: Ruler,
  shield: Shield,
  'shopping-cart': ShoppingCart,
  snowflake: Snowflake,
  sparkles: Sparkles,
  type: Type,
  'volume-2': Volume2,
  zap: Zap,
};

interface Props {
  name?: string;
  size?: number | string;
  className?: string;
  strokeWidth?: number;
}

export function Icon({ name, size = 24, className, strokeWidth = 2 }: Props) {
  const C = (name && icons[name]) || CircleHelp;
  return <C size={size} className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}
